# Command logfile created by Lynx 2.8.6rel.5 (09 May 2007)
# Arg0 = lynx
# Arg1 = -cmd_log=tracking.script
# Arg2 = http://www.ae5000.ru/senders/state_delivery/
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Up Arrow
key Up Arrow
key Up Arrow
key Up Arrow
key Up Arrow
key Up Arrow
key Up Arrow
key Up Arrow
key Up Arrow
key Up Arrow
key Up Arrow
key Up Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Down Arrow
key Up Arrow
key 0
key 1
key .
key 0
key 4
key .
key 2
key 0
key 1
key 4
key <delete>
key <delete>
key <delete>
key <delete>
key <delete>
key <delete>
key <delete>
key <delete>
key <delete>
key <delete>
key <delete>
key <delete>
key <delete>
key <delete>
key <delete>
key <delete>
key <delete>
key End
key <tab>
key <tab>
key q
key ^J
